version: "3"
services:
  # Setup frontend/client container
  frontend:
    stdin_open: true
    container_name: sticky_notes_web
    build:
      context: ./sticky_notes_frontend
      dockerfile: Dockerfile
    environment:
      - CLIENT_APP_PORT=${CLIENT_APP_PORT}
    expose:
      - ${CLIENT_APP_PORT}
    image: aledosa/sticky_notes_web
    ports:
      - ${CLIENT_APP_PORT}:${CLIENT_APP_PORT}
    volumes:
      - ./sticky_notes_frontend:/usr/src/app-frontend
    links:
      - backend
    command: yarn start

  # Setup backend/server/node container
  backend:
    container_name: sticky_notes_server
    build: ./sticky_notes_backend
    environment:
      API_HOST: ${API_HOST}
      SERVER_APP_PORT: ${SERVER_APP_PORT}
    expose:
      - ${SERVER_APP_PORT}
    image: aledosa/sticky_notes_server
    ports:
      - ${SERVER_APP_PORT}:${SERVER_APP_PORT}
    volumes:
      - ./sticky_notes_backend:/usr/src/app-backend
    command: npm start
